# Generated by Django 5.1 on 2025-10-25 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lienzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó este lienzo.')),
                ('nombre', models.CharField(default='Nuevo Lienzo', help_text='Nombre descriptivo para el lienzo.', max_length=100)),
                ('ancho', models.IntegerField()),
                ('alto', models.IntegerField()),
                ('color_fondo', models.CharField(max_length=100)),
                ('ancho_eje_x', models.FloatField(default=16)),
                ('ancho_eje_y', models.FloatField(default=16)),
                ('zoom', models.FloatField(default=16)),
            ],
        ),
        migrations.CreateModel(
            name='Derivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#2ca02c', help_text='Color de la línea de la derivada (código hex).', max_length=7)),
                ('grosor_linea', models.IntegerField(default=1, help_text='Grosor de la línea de la derivada en píxeles.')),
                ('punto_x', models.FloatField(help_text='El valor x donde se traza la línea tangente/derivada.')),
                ('funcion', models.ForeignKey(help_text='La Función a la que pertenece esta Derivada.', on_delete=django.db.models.deletion.CASCADE, related_name='derivadas', to='graficas.funcion')),
            ],
        ),
        migrations.CreateModel(
            name='Integral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graficas.funcion')),
            ],
        ),
        migrations.AddField(
            model_name='funcion',
            name='lienzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graficas.lienzo'),
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='Coordenada X del punto.')),
                ('y', models.FloatField(help_text='Coordenada Y del punto.')),
                ('color', models.CharField(default='#d62728', help_text='Color del punto (código hex).', max_length=7)),
                ('etiqueta', models.CharField(blank=True, help_text="Etiqueta opcional para el punto (ej. 'Máximo', 'A').", max_length=50, null=True)),
                ('lienzo', models.ForeignKey(help_text='El Lienzo al que pertenece este Punto.', on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='graficas.lienzo')),
            ],
        ),
    ]
