# Generated by Django 5.1 on 2025-10-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lienzo',
            name='alto',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='lienzo',
            name='ancho',
            field=models.IntegerField(default=500),
        ),
    ]
