# Generated by Django 5.2.7 on 2025-10-26 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0002_alter_lienzo_alto_alter_lienzo_ancho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#1f77b4', help_text='Color de la línea (código hex).', max_length=7)),
                ('grosor_linea', models.IntegerField(default=2, help_text='Grosor de la línea en píxeles.')),
                ('lienzo', models.ForeignKey(help_text='El Lienzo al que pertenece esta Recta.', on_delete=django.db.models.deletion.CASCADE, related_name='rectas', to='graficas.lienzo')),
                ('p1', models.ForeignKey(help_text='Punto inicial (x1, y1) de la Recta.', on_delete=django.db.models.deletion.CASCADE, related_name='rectas_p1', to='graficas.punto')),
                ('p2', models.ForeignKey(help_text='Punto final (x2, y2) de la Recta.', on_delete=django.db.models.deletion.CASCADE, related_name='rectas_p2', to='graficas.punto')),
            ],
        ),
    ]
