# Generated by Django 5.2.7 on 2025-10-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0003_recta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('padre', models.ForeignKey(blank=True, help_text='Referencia al nodo padre. Es nulo para la raíz del árbol.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='graficas.nodo')),
            ],
        ),
    ]
