# Generated by Django 5.2.7 on 2025-10-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0004_nodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nueva Matriz', max_length=255)),
                ('datos_matriz', models.JSONField(default=list)),
                ('filas', models.IntegerField(default=10)),
                ('columnas', models.IntegerField(default=10)),
                ('estado_actual', models.CharField(default='Inicial', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Matrices',
            },
        ),
    ]
