# Generated by Django 5.2.7 on 2025-10-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0005_matriz'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriz',
            name='generacion',
            field=models.IntegerField(default=0),
        ),
    ]
