# Generated by Django 5.2.7 on 2025-10-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0006_matriz_generacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriz',
            name='blue_rule',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='brown_rule',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='gray_rule',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='green_rule',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='intervalo_almacenamiento',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='matriz',
            name='red_rule',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='velocidad',
            field=models.IntegerField(default=250),
        ),
    ]
