# Generated by Django 5.2.7 on 2025-11-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0007_matriz_blue_rule_matriz_brown_rule_matriz_gray_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='matriz_ac',
            field=models.OneToOneField(blank=True, help_text='La Matriz de estado inicial del Autómata Celular (solo para nodos hoja).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodo_asociado', to='graficas.matriz'),
        ),
    ]
