# Generated by Django 5.2.7 on 2025-11-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0008_nodo_matriz_ac'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='is_leaf',
            field=models.BooleanField(default=False, help_text='Indica si el nodo es una hoja (no tiene afluentes).'),
        ),
    ]
