# Generated by Django 5.2.7 on 2025-11-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0009_nodo_is_leaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriz',
            name='rule_1_color_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_1_color_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_1_color_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_2_color_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_2_color_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_2_color_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_3_color_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_3_color_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_3_color_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_4_color_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_4_color_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_4_color_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_5_color_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_5_color_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matriz',
            name='rule_5_color_3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
