# Generated by Django 5.2.7 on 2025-11-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0010_matriz_rule_1_color_1_matriz_rule_1_color_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriz',
            name='altura_regla_1',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='matriz',
            name='altura_regla_2',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='matriz',
            name='altura_regla_3',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='matriz',
            name='altura_regla_4',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='matriz',
            name='altura_regla_5',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_1_color_1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_1_color_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_1_color_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_2_color_1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_2_color_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_2_color_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_3_color_1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_3_color_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_3_color_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_4_color_1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_4_color_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_4_color_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_5_color_1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_5_color_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_5_color_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
