# Generated by Django 5.2.7 on 2025-11-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0011_matriz_altura_regla_1_matriz_altura_regla_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriz',
            name='rule_1_color_1',
            field=models.CharField(blank=True, default='red', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_1_color_2',
            field=models.CharField(blank=True, default='red', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_1_color_3',
            field=models.CharField(blank=True, default='red', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_2_color_1',
            field=models.CharField(blank=True, default='blue', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_2_color_2',
            field=models.CharField(blank=True, default='blue', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_2_color_3',
            field=models.CharField(blank=True, default='blue', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_3_color_1',
            field=models.CharField(blank=True, default='green', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_3_color_2',
            field=models.CharField(blank=True, default='green', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_3_color_3',
            field=models.CharField(blank=True, default='green', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_4_color_1',
            field=models.CharField(blank=True, default='brown', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_4_color_2',
            field=models.CharField(blank=True, default='brown', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_4_color_3',
            field=models.CharField(blank=True, default='brown', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_5_color_1',
            field=models.CharField(blank=True, default='gray', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_5_color_2',
            field=models.CharField(blank=True, default='gray', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='rule_5_color_3',
            field=models.CharField(blank=True, default='gray', max_length=200),
        ),
    ]
