# Generated by Django 5.2.7 on 2025-11-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0012_alter_matriz_rule_1_color_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriz',
            name='escala',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='matriz',
            name='escala_vista_plana',
            field=models.IntegerField(default=1),
        ),
    ]
