# Generated by Django 6.0.1 on 2026-03-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0013_matriz_escala_matriz_escala_vista_plana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriz',
            name='altura_regla_1',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='altura_regla_3',
            field=models.IntegerField(blank=True, default=8),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='altura_regla_4',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='altura_regla_5',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
