# Generated by Django 6.0.1 on 2026-06-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0014_alter_matriz_altura_regla_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='numero_de_nodo',
            field=models.IntegerField(blank=True, default=0, help_text='Número de nodo.', null=True),
        ),
        migrations.AddField(
            model_name='nodo',
            name='tipo',
            field=models.CharField(blank=True, default='Grupo', help_text='Tipo de nodo.', max_length=50, null=True),
        ),
    ]
